In [1]:
from segnlp.datasets import PE
from segnlp.data import Batch

Using backend: pytorch


In [2]:
pe = PE(
        tasks = ["seg+label", "link", "link_label"],
        prediction_level = "token",
        sample_level = "paragraph",
        label_ams = True
)

{'seg': ['O', 'B', 'I'], 'label': ['None', 'MajorClaim', 'Claim', 'Premise'], 'seg+label': ['O', 'B_MajorClaim', 'B_Claim', 'B_Premise', 'I_MajorClaim', 'I_Claim', 'I_Premise'], 'link': [-11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], 'link_label': ['None', 'root', 'support', 'attack']}


Preprocessing Persuasive Essays:   0%|          | 0/402 [00:00<?, ?it/s]

In [3]:
batch = Batch(pe._samples[:10])

In [4]:
batch.get("seg","link")

[tensor([], dtype=torch.int64), tensor([0]), tensor([0, 0, 0, 0]), tensor([1, 1, 4, 4, 4]), tensor([0]), tensor([], dtype=torch.int64), tensor([0]), tensor([4, 4, 4, 4, 4]), tensor([5, 0, 5, 5, 5, 5]), tensor([0, 1])]


tensor([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 1, 4, 4, 4, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [4, 4, 4, 4, 4, 0],
        [5, 0, 5, 5, 5, 5],
        [0, 1, 0, 0, 0, 0]])

In [5]:
l = batch._target_samples[-2].df["link"].values
l

array([-1, -1,  5,  5,  5,  5,  5,  5,  5,  5, -1,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1, -1, -1, -1,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5, -1,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5, -1,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5, -1, -1, -1, -1,
       -1, -1, -1,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5, -1])

In [6]:
str(batch._target_samples[-2])

'secondly , it is crucial to keep one ’s identity for they need a connection back to their country as well as teach their children their value of origin . for instance , children immigrated to a new country will face social troubles in school with new friends . in this new environment , parent should find friends coming from their same country so that they can socialize in a very familiar manner as feeling being home . fail to create this familiarity makes them felt isolated , in the extreme can lead to social disorder like autism . hence , it is clear that keeping the cultural traditions in the destination countries is tremendous important .'

In [7]:
batch._target_samples[-2]._n_segs()

6

In [8]:
l[l!= -1] - 6

array([-1, -1, -1, -1, -1, -1, -1, -1, -6, -6, -6, -6, -6, -6, -6, -6, -6,
       -6, -6, -6, -6, -6, -6, -6, -6, -6, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [9]:
from segnlp.nlp import NLP


doc = "This is a not a segment. However, here starts a segement. This, right after this comma, is also a segment."
nlp = NLP()
sample = nlp(doc)


In [10]:
from segnlp.utils import RangeDict

span2label = RangeDict({
    (0, 33): {'span_id': 0, 'seg_id': -1, 'label': 'None', 'link': -1, 'link_label': 'None'}, 
    (34, 57): {'span_id': 1, 'seg_id': 0, 'label': 'A', 'link': 1, 'link_label': 'A'},
    (58, 87): {'span_id': 2, 'seg_id': -1, 'label': 'None', 'link': -1, 'link_label': 'None'}, 
    (88, 106): {'span_id': 3, 'seg_id': 1, 'label': 'B', 'link': 1, 'link_label': 'root'}, 
})

task_labels = {
                "seg": ["O", "B", "I"],
                "label": ["None", "A", "B"],
                "link_label": ["root", "A"]
                }
sample.add_span_labels(
                            span2label, 
                            task_labels = task_labels, 
                            label_ams = True
)

In [11]:
sample.get("seg","str")

KeyError: 'Getting values for str is not supported for seg level.'

In [ ]:
import torch
import numpy as np
from torch.nn.utils.rnn import pad_sequence


a = torch.LongTensor([1,2,3])
b = torch.LongTensor([1,2,3,4])
pad_sequence([a,b], batch_first = True)

In [ ]:
x = list(range(10))
y = list(range(3,6))
print(x, y)

range(max(x[0], y[0]), min(x[-1], y[-1])+1)